# Generated by Django 4.1.3 on 2024-12-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('diferencia_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_actual', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
